import React from "react";
import type { Metadata } from "next";
import { Inter, Libre_Caslon_Display } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

// Define fonts
const inter = Inter({ subsets: ["latin"] });
const libreCaslon = Libre_Caslon_Display({
  subsets: ["latin"],
  weight: "400",
});

// Define metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Main layout component
export default function RootLayout({
  children,
  font = "inter",
}: Readonly<{
  children: React.ReactNode;
  font?: "libreCaslon" | "inter";
}>) {
  // Select the appropriate font class based on the provided prop
  const fontClass =
    font === "libreCaslon" ? inter.className : libreCaslon.className;

  return (
    <html lang="en">
      <body className={fontClass}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
